from django.urls import path
from . import views
urlpatterns = [
    path("", views.demo_entry, name="demo_entry"),
    path("switch-role/<str:role_name>/", views.switch_role, name="switch_role"),


    path('', views.login_view, name='home'),
    path('generate-invoice/<int:student_id>/', views.generate_fee_invoice, name='generate_invoice'),
    path('generate-result/<int:student_id>/', views.generate_result_pdf, name='generate_result'),
    path("results/add/", views.add_result, name="add_result"),
    path("results/", views.result_list, name="result_list"),
    path("results/edit/<int:pk>/", views.edit_result, name="edit_result"),
    path("results/delete/<int:pk>/", views.delete_result, name="delete_result"), 


    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('select-dashboard/', views.select_dashboard, name='select_dashboard'),
    path('redirect-dashboard/', views.redirect_dashboard, name='redirect_dashboard'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('teacher-dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('student-dashboard/', views.student_dashboard, name='student_dashboard'),
    path('students/', views.students_list, name='students_list'),
    path('students/add/', views.students_create, name='students_create'),
    path('students/edit/<int:pk>/', views.students_update, name='students_update'),
    path('students/delete/<int:pk>/', views.students_delete, name='students_delete'),
    path('teachers/', views.teachers_list, name='teachers_list'),
    path('teachers/add/', views.teachers_create, name='teachers_create'),
    path('teachers/edit/<int:pk>/', views.teachers_update, name='teachers_update'),
    path('teachers/delete/<int:pk>/', views.teachers_delete, name='teachers_delete'),
    path('subjects/', views.subjects_list, name='subjects_list'),
    path('subjects/add/', views.subjects_create, name='subjects_create'),
    path('subjects/edit/<int:pk>/', views.subjects_update, name='subjects_update'),
    path('subjects/delete/<int:pk>/', views.subjects_delete, name='subjects_delete'),
    path('fees/', views.fees_list, name='fees_list'),
    path('fees/add/', views.fees_create, name='fees_create'),
    path('fees/edit/<int:pk>/', views.fees_update, name='fees_update'),
    path('fees/delete/<int:pk>/', views.fees_delete, name='fees_delete'),
    path('events/', views.events_list, name='events_list'),
    path('events/add/', views.events_create, name='events_create'),
    path('events/edit/<int:pk>/', views.events_update, name='events_update'),
    path('events/delete/<int:pk>/', views.events_delete, name='events_delete'),
    path('schools/', views.schools_list, name='schools_list'),
    path('schools/add/', views.schools_create, name='schools_create'),
    path('schools/edit/<int:pk>/', views.schools_update, name='schools_update'),
    path('schools/delete/<int:pk>/', views.schools_delete, name='schools_delete'),  
]
